site_name: Brian Bascom
site_url: https://bascom16.github.io
theme:
  name: material
  # font:
  #   text: Merriweather Sans
  #   code: Red Hat Mono
  logo: assets/blur.svg
  favicon: assets/blur.svg
  # features:
  #   - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      # toggle:
      #   icon: material/weather-night
      #   name: Switch to Dark Mode
      primary: 'custom'
      accent: 'custom'
    # Dark Mode
    # - scheme: slate
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to Light Mode
    #   primary: 'custom'
    #   accent: 'custom'

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/brian-bascom
    - icon: simple/github
      link: https://github.com/bascom16

extra_css:
  - stylesheets/colors.css
  - stylesheets/extra.css
  - stylesheets/card_filters.css

copyright: Copyright &copy; 2025 Brian Bascom

nav:
  - Bio: index.md
  - Projects: portfolio/projects_simplified.md
  - MAGICC Lab: magicc.md
  - Github: github.md

plugins:
  - search
  - redirects:
      redirect_maps:
        'github.md': 'https://github.com/bascom16'
  - tags

# extra_javascript:
#   - https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js
#   - javascript/isotope-init.js