name: ci
on:
  push:
    branches:
      - main  # Or master, depending on your branch name
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install --upgrade mkdocs-material mkdocs-redirects

      # This is the key change:
      # It uses your secret token to deploy to the correct repository and branch.
      - name: Deploy documentation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force \
            --remote-url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/bascom16/bascom16.github.io.git \
            --remote-branch main