name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # This is the new caching step from the official documentation.
      # It ensures that our packages are fresh.
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            ${{ runner.os }}-pip-

      # This command now uses --upgrade to be extra sure we get the latest versions.
      - name: Install dependencies
        run: pip install --upgrade mkdocs mkdocs-material mkdocs-redirects

      - name: Deploy documentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force \
            --remote-url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/bascom16/bascom16.github.io.git \
            --remote-branch main